### ISSUE TITLE
Well Recieved

### ISSUE THREAD

**Issue by idkjs** [duyngb/simple-password#12]
This is some boss code, sir. Thanks for sharing it so it can be studied.

Just and fyi, seems the local dev webpack set up is not quite right. It renders the file tree instead of the app.

Thanks again!

**Comment by duyngb** [comment]
My bad. Looks like I forgot something...

ATTM, this is a temporary fix, by running manually:

```
# Run this at repo root
npx webpack serve --config webpack.config.dev.js --static docs
```
